sudo: true
dist: bionic
os: linux
language: bash
services:
  - docker
before_install:
  - docker build -t mod_statsd -f .devcontainer/Dockerfile .
script:
  -  docker run -v "$TRAVIS_BUILD_DIR":/mod_statsd -i mod_statsd bash -c "cd /mod_statsd && make && ls"